name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Copy files
        run: |
          mkdir -p deploy
          cp -fv index.html ./deploy/
          cp -frv img ./deploy/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          cname: shamil.ru
          force_orphan: true
          user_name: 'shamil-ru'
          user_email: 'shamil-ru@users.noreply.github.com'
